require_relative 'page_objects/elements/clients_elements'
require_relative 'page_objects/elements/login_elements'
require_relative 'page_objects/elements/home_elements'
require_relative 'page_objects/elements/side_panel_elements'
require_relative 'utils/enums'
require_relative 'utils/helpers'
require_relative 'page_objects/page_actions/home_page'
require_relative 'page_objects/page_actions/clients_page'